### ISSUE TITLE
It this package identical to `tco`?

### ISSUE THREAD

**Issue by hongyi-zhao** [0scarB/tail-recursive#1]
A few days ago, I also noticed other similar projects, such as [`tco`](https://github.com/baruchel/tco) and [`tail-recursion`](https://pypi.org/project/tail-recursion/). It seems that they are all very similar, even identical. Am I right? See the related discussion [here](https://groups.google.com/g/comp.lang.python/c/dL1gyqU_D2k/m/gqvlfJySDwAJ). 

Regards,
HZ

**Comment by 0scarB** [comment]
Hi, thanks for taking an interest and no, they are all distinct packages.

This packages uses the `@tail_recursive` decorator to replace decorated functions with a callable. The resulting callable has a `tail_call` method that can be used to call the function using tail recursion. E.g.:
```python
@tail_recursive
def count_down(n):
     print(n)
     return None if n == 1 else count_down.tail_call(n - 1)
```

I haven't used the two other packages so I can't really speak much on their implementation but they seem to do the following:
- _tco_ uses the `self` keyword argument to pass in a callable to the function which can be used for tail recursion.
- _tail-recursion_ uses the `TailRecursion` class as a callable for tail recursion.

This package tries to focus on having a very simple API and supports some additional features out of the box such as operator overloading (some more work definitely needs to be done to more fully support this feature) and nested calls. E.g.:
```python
@tail_recursive
def factorial(n):
   if n == 0:
       return 1
   # Supports (some) operator overloading
   return n * factorial.tail_call(n - 1)
   
# https://en.wikipedia.org/wiki/Ackermann_function
@tail_recursive
def ackermann(m, n):
   if m == 0:
       return n + 1
   if n == 0:
       return ackermann.tail_call(m - 1, 1)
   # Supports nested calls
   return ackermann.tail_call(m - 1,  ackermann.tail_call(m, n - 1))
```
This however comes with a performance cost and can be disabled  with `@tail_recursive(feature_set=FeatureSet.BASE)`.

Unfortunately I didn't build any benchmarks to support this claim. If you're looking for the fastest package then maybe compare your use case against the different packages using the `timeit` module or another benchmarking package. I suspect that this one will be pretty slow without `feature_set=FeatureSet.BASE`.

Side note: I haven't tested this package lately so if you decide to use it and find that something is broken then it'd be cool if you could let me know.
